name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *' # 每天午夜运行
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write # 允许 GitHub Actions 写入仓库

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 获取完整历史，避免 rebase 问题

      - name: Setup Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Add Upstream Repository
        run: |
          git remote add upstream https://github.com/ibuzao/ibuzao.github.io.git || echo "Upstream already exists"
          git fetch upstream --prune

      - name: Merge Upstream Changes
        run: |
          git checkout main || git checkout -b main
          git merge upstream/main --allow-unrelated-histories || true
          git push origin main
